"""
predict.py
----------
Runs inference on a single audio file using the best trained checkpoint.
Useful for testing the model on your own voice recordings, or as the
backend for a demo app (e.g. Streamlit).

Usage:
    python src/predict.py --file path/to/audio.wav
    python src/predict.py --file path/to/audio.wav --top_k 3
"""

import os
import sys
import argparse
import numpy as np
import torch
import torch.nn.functional as F

sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from config import BEST_MODEL_PATH, NUM_CLASSES, SAMPLE_RATE, DURATION
from feature_extraction import load_and_trim_audio, fix_length, extract_features_sequence
from model import EmotionCNN


def load_trained_model(checkpoint_path: str = BEST_MODEL_PATH, device: torch.device = None):
    """
    Loads the trained EmotionCNN from a checkpoint saved by train.py.

    Returns
    -------
    model : EmotionCNN in eval mode
    class_names : list[str], the emotion label order used by the model
    device : torch.device
    """
    if device is None:
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    if not os.path.exists(checkpoint_path):
        raise FileNotFoundError(
            f"No trained model found at {checkpoint_path}. Run train.py first."
        )

    # weights_only=False is safe here: this checkpoint was generated by
    # train.py in this same project, not downloaded from an untrusted source.
    checkpoint = torch.load(checkpoint_path, map_location=device, weights_only=False)

    model = EmotionCNN(num_classes=NUM_CLASSES).to(device)
    model.load_state_dict(checkpoint["model_state_dict"])
    model.eval()

    class_names = checkpoint.get("label_classes", None)
    if class_names is None:
        raise ValueError(
            "Checkpoint is missing 'label_classes' — retrain with the current "
            "train.py so class order is saved alongside the model weights."
        )

    return model, class_names, device


def preprocess_audio_file(filepath: str) -> torch.Tensor:
    """
    Applies the exact same preprocessing used during training (trim silence,
    fix length, mel-spectrogram) to a single new audio file, and returns it
    as a model-ready tensor with batch + channel dimensions added.
    """
    if not os.path.exists(filepath):
        raise FileNotFoundError(f"Audio file not found: {filepath}")

    y = load_and_trim_audio(filepath, sr=SAMPLE_RATE)
    y = fix_length(y, sr=SAMPLE_RATE, duration=DURATION)
    mel_db = extract_features_sequence(y, sr=SAMPLE_RATE)  # shape: (channels, n_mels, time_steps)

    tensor = torch.tensor(mel_db, dtype=torch.float32)
    tensor = tensor.unsqueeze(0)  # -> (1, channels, n_mels, time_steps)
    return tensor


@torch.no_grad()
def predict_emotion(filepath: str, model=None, class_names=None, device=None, top_k: int = 3) -> dict:
    """
    Predicts the emotion of a single audio file.

    Parameters
    ----------
    filepath : str
        Path to a .wav file to classify.
    model, class_names, device : optional
        Pass these in to reuse an already-loaded model across multiple
        predictions (e.g. in a Streamlit app) instead of reloading from
        disk every call. If omitted, loads fresh from BEST_MODEL_PATH.
    top_k : int
        Number of top predictions to return, ranked by confidence.

    Returns
    -------
    dict with keys:
        'predicted_emotion' : str, the single most likely emotion
        'confidence'        : float, probability of the top prediction
        'top_k'             : list of (emotion, probability) tuples
    """
    if model is None or class_names is None or device is None:
        model, class_names, device = load_trained_model()

    input_tensor = preprocess_audio_file(filepath).to(device)
    logits = model(input_tensor)
    probs = F.softmax(logits, dim=1).squeeze(0).cpu().numpy()

    top_k = min(top_k, len(class_names))
    top_indices = np.argsort(probs)[::-1][:top_k]
    top_predictions = [(class_names[i], float(probs[i])) for i in top_indices]

    return {
        "predicted_emotion": class_names[top_indices[0]],
        "confidence": float(probs[top_indices[0]]),
        "top_k": top_predictions,
    }


def parse_args():
    parser = argparse.ArgumentParser(description="Predict emotion from a single audio file.")
    parser.add_argument("--file", type=str, required=True, help="Path to a .wav file.")
    parser.add_argument("--top_k", type=int, default=3, help="Number of top predictions to show.")
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()

    result = predict_emotion(args.file, top_k=args.top_k)

    print(f"\nFile: {args.file}")
    print(f"Predicted emotion: {result['predicted_emotion']}  "
          f"(confidence: {result['confidence']*100:.1f}%)")
    print(f"\nTop {args.top_k} predictions:")
    for emotion, prob in result["top_k"]:
        bar = "#" * int(prob * 40)
        print(f"  {emotion:<12} {prob*100:5.1f}%  {bar}")